/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyect;

import java.rmi.RemoteException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author anita
 */
public class InicioUsuario extends javax.swing.JFrame {

    /**
     * Creates new form InicioUsuario
     */
    private ClienteObjetoRemoto chatClient;
    Chat chatgui;
    ClienteRMI objetoCliente;
    
    public InicioUsuario() {
        
        initComponents();
        setLocationRelativeTo(null);
        
    }

    InicioUsuario(ClienteObjetoRemoto chatClient) {
        initComponents();
        setLocationRelativeTo(null);
        this.chatClient=chatClient;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel1.setText("Inserta nombre de usuario:");

        nombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreUsuario))
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnEntrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnEntrar)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        
        
      
        String nombre = nombreUsuario.getText();
        nombre=nombre.replace(" ","");
        
        if(nombre.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Favor de ingresar un nombre");
        }
        else
        {
           String nuevoNombre= nombre+"_"+GenerarID(nombre);
           JOptionPane.showMessageDialog(null, "Su usuario ID es:\n"+nuevoNombre);
        chatgui = new Chat(chatClient,nuevoNombre);

        this.dispose();
        chatgui.setVisible(true); 
        }
        
        
        
            
        
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    public String GenerarID(String nombre)
    {
        String nuevoNombreUsuario;
        char [] chars = (nombre+"0123456789ABCDefgHIGKLMNopqRSTUVWXYz").toCharArray();
        Random r = new Random();
        int valorInicio = r.nextInt(9)+1;
        int valorFinal = r.nextInt(999)+1;
        int charsLength = chars.length;
        Random random = new Random();
        StringBuffer buffer = new StringBuffer();
        for (int i=0;i<3;i++){
           buffer.append(chars[random.nextInt(charsLength)]);
        }
        nuevoNombreUsuario= String.valueOf(valorInicio)+buffer.toString()+String.valueOf(valorFinal);
        
        
        //System.out.println("IDRANDOM " + nuevoNombreUsuario);
        return nuevoNombreUsuario;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioUsuario().setVisible(true);
            }
        });
    }
    
//    public void realizarConexion()
//    {
//         try {                   
//        
//                                String nombre = nombreUsuario.getText();
//				if(nombre.length() != 0){
//                                 
//                                       chatgui.setTitle(nombre + "'s console ");
//                                       chatgui.mensaje.setText("");
//                                       //chatgui.areaChat.append("username : " + nombre + " connecting to chat...\n");
//                                       chatgui.obtenerConexion(nombre);
//                                       if(!chatClient.connectionProblem){
//                                           chatgui.btnBuscarArchivo.setEnabled(false);
//                                           chatgui.btnEnviar.setEnabled(true);
//                                 
//				}
//				else{
//					JOptionPane.showMessageDialog(chatgui.areaChat, "Enter your name to Start");
//				}
//                                       
//                }
//                                   } catch (RemoteException ex) {
//                                       Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
//                                   }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
